container:
  image: rust:latest
  kvm: true

test_task:
  registry_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  target_cache:
    folder: target
    fingerprint_script:
      - rustc --version
      - cat Cargo.lock
  toolchain_script: rustup component add clippy rustfmt
  build_script: cargo build
  test_script: cargo test
  fmt_script: cargo fmt --check
  clippy_script: cargo clippy
  before_cache_script: rm -rf $CARGO_HOME/registry/index
