[package]
name = "alioth-macros"
version = "0.7.0"
edition.workspace = true
description = "Proc macros for Alioth"
repository.workspace = true
authors.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
