[package]
name = "alioth-macros"
version = "0.1.0"
edition = "2021"
description = "Proc macros for Alioth"
repository.workspace = true
authors.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2" }
quote = { version = "1" }
