[package]
name = "serde-aco"
version = "0.8.0"
edition.workspace = true
description = "Serialization and deserialization library for Alioth command-line options."
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde-aco-derive.workspace = true

[dev-dependencies]
assert_matches.workspace = true
serde_bytes = "0.11"
